{% set version = "2.6.11" %}
{% set version_list = version.split('.') %}
{% set tarversion = version_list[0]+version_list[1]+'r'+version_list[2] %}
{% set name = "nauty" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ tarversion }}.tar.gz
  url: http://users.cecs.anu.edu.au/~bdm/nauty/nauty{{ tarversion }}.tar.gz
  sha256: 5ed401917f641af6bf7617a18561b8f1ff5d6563268d815a054786c1ceace617
  patches:
    - minmax.patch
    - ar.patch

build:
  number: 1000
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev              # [win]
    - lld                   # [win]
    - m2-make               # [win]
    - m2-automake-wrapper   # [win]
    - m2-libtool            # [win]
    - m2-autoconf           # [win]
    - posix                 # [win]
  host:

test:
  commands:
    - addedgeg -help

about:
  home: http://users.cecs.anu.edu.au/~bdm/nauty/
  license: other
  license_file: COPYRIGHT
  summary: nauty and Traces are programs for computing automorphism groups of graphs and digraphs.

extra:
  recipe-maintainers:
    - isuruf
