{% set version = "2.6.11" %}
{% set version_list = version.split('.') %}
{% set tarversion = version_list[0]+version_list[1]+'r'+version_list[2] %}
{% set name = "nauty" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ tarversion }}.tar.gz
  url: http://users.cecs.anu.edu.au/~bdm/nauty/nauty27rc1.tar.gz
  sha256: 43a68572b8d32c1def1c263dfd959ea928f2d2c6c5f20aa970269e9e31dc9a45
  patches:
    - time.diff

build:
  number: 1000
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - clangdev              # [win]
    - lld                   # [win]
    - m2-make               # [win]
    - m2-automake-wrapper   # [win]
    - m2-libtool            # [win]
    - m2-autoconf           # [win]
    - posix                 # [win]
  host:

test:
  commands:
    - addedgeg -help

about:
  home: http://users.cecs.anu.edu.au/~bdm/nauty/
  license: other
  license_file: COPYRIGHT
  summary: nauty and Traces are programs for computing automorphism groups of graphs and digraphs.

extra:
  recipe-maintainers:
    - isuruf
